### ISSUE TITLE
setState typing problem

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#10]
The parameters provided to setState must contain all the fields defined in `TState`. Is it possible to override the type (or create another type) with macro to make all fields optional (for the setState function parameter only)?

Two workarounds for now:
1. use untyped (e.g. `setState(untyped {key:value});`), but this defeats the purpose of using haxe's type system
2. manually define all state fields as optional, but this is also not perfect

**Comment by dpeek** [comment]
You need to define your state typedef with all fields optional:

``` haxe
typedef MyState = {
    @:optional var enabled:Bool;
    @:optional var focused:Bool;
}
```

We can look into some kind of macro utility to help here but unfortunately there are no build macros on typedefs.

**Comment by zabojad** [comment]
You could perhaps also make some kind of factory method that initializes a state object with default values, to avoid having to set all the fields as optional (and that could probably be a macro)... Also, I do prefer this syntax:

```
typedef MyState = {
    ? enabled : Bool,
    ? focused : Bool
}
```

**Comment by dpeek** [comment]
When we call setState we don't want to pass default values for anything that isn't provided, this needs to be compile time somehow. I'll look into it.

As for syntax, that's entirely up to you :)

**Comment by kevinresol** [comment]
@dpeek your optional fields solution is what I mentioned in workaround no.2
That isn't really perfect because we may actually want to specify some fields as mandatory.

I am not sure if @:genericBuild can help here, to generate a concrete `TStateAllOptional` type for each generic type `TState`, and use that in the setState function. But that would create a lot of concrete generic types of ReactComponent, which is not really necessary in the js target.

**Comment by kevinresol** [comment]
Not much can be done on this.
