### ISSUE TITLE
Loading a JS module from Haxe in the same project

### ISSUE THREAD

**Issue by fullofcaffeine** [massiveinteractive/haxe-react#125]
Hi!

I'm currently experimenting with `haxe-react` and https://github.com/jasononeil/webpack-haxe-loader. 

I created a skeleton bare-bones React app with https://github.com/facebook/create-react-app and added the `haxe-loader` config in the webpack config by following the example in https://github.com/elsassph/webpack-haxe-example/. 

I figured CRA was the bleeding-edge way of quickly bootstrapping a React app with best-practices from the community, and wanted to see how hard it would be to integrate React components generated by Haxe. It seems to work great! Here's the repo for the experiment: https://github.com/fullofcaffeine/haxe-react-tink-web-cra.

However, I'd also like to experiment using ES/TS React modules from Haxe React modules and vice-versa*[0]. I'm currently trying with plain ES React modules from Haxe by using a Haxe extern:

1) The actual implementation is here: https://github.com/fullofcaffeine/haxe-react-tink-web-cra/blob/master/src/Test.js;
2) The extern here: https://github.com/fullofcaffeine/haxe-react-tink-web-cra/blob/master/src/Test.hx.

But WebPack complains with:

```
Failed to compile.

./node_modules/haxe-loader?frontend/Test
Module not found: Can't resolve 'Test' in '/home/fullofcaffeine/workspace/code/product-creation-stack-templates/haxe-react-tink-web-cra'
```

The problem, from what I understand, is that `@:jsRequire` is not webpack-aware, and even if I load `Test` in https://github.com/fullofcaffeine/haxe-react-tink-web-cra/blob/master/src/Root.hx#L20, it is not found by the `require` generated by `@:jsRequire`. 

Is there a way to work around that? Am I missing something? Any insights appreciated!

_*[0] Why? Well, Haxe is my preferred way to code the app, but perhaps for some reason a third-party lib is hard to use from Haxe code or maybe for that specific component/solution TS/ES could be a better choice. So, basically having the best of both worlds, and being able to fallback to whatever gives me the best productivity at the time, given the requirements._

**Comment by kLabz** [comment]
There's a few things going on here:

* `@:jsRequire('Test')` will try to find a package, not a local module ; `@:jsRequire('./Test')` should work a little better
* Webpack doesn't resolve `'./Test'` as per your current configuration (sorry, too lazy to eject+edit or find the file myself) ; you can use `@:jsRequire('./src/Test')` to make it work for now
* you do `export default Test` in `Test.js` so in `Root.hx` you have to access the "default" field (for example with `setState({ component: untyped Test['default'] });`) to avoid a runtime error

**Comment by fullofcaffeine** [comment]
> @:jsRequire('Test') will try to find a package, not a local module ; @:jsRequire('./Test') should work a little better

Ah, true, forgot about absolute `require`s looking for packages!

> Webpack doesn't resolve './Test' as per your current configuration (sorry, too lazy to eject+edit or find the file myself) ; you can use @:jsRequire('./src/Test') to make it work for now

Thanks! That fixes it!

> you do export default Test in Test.js so in Root.hx you have to access the "default" field (for example with setState({ component: untyped Test['default'] });) to avoid a runtime error

Thanks! I figured it's actually better to add it to the `@:jsRequire` as in `@jsRequire('./src/Test','default')`. Then I can refer to `Test` only when loading it in `Root.hx`.

I think that settles everything, thanks a lot for the help :)

**Comment by elsassph** [comment]
Oh yes that was a tricky one, requires are relative to the hxml file! The `Webpack` Haxe class has a `require` which will be adjusted to the current file but it can't be used on an extern. It needs a more obvious mention in the doc.

**Comment by kLabz** [comment]
> I figured it's actually better to add it to the `@:jsRequire` as in `@:jsRequire('./src/Test','default')`.

Yeah, exactly :) I needed a little more coffee before remembering that :D
