### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#14]
https://facebook.github.io/react/docs/jsx-spread.html

It is useful in [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html#content)

**Comment by elsassph** [comment]
Yes it is a known missing feature of the JSX parser.

**Comment by zabojad** [comment]
Also useful there: https://github.com/reactjs/react-router/blob/master/docs/API.md#createelementcomponent-props

**Comment by elsassph** [comment]
I rewrote the parser with support for spread attributes among other improvements - this should land soon on github.

**Comment by zabojad** [comment]
Excellent! That will help a lot with making externs and wrapper components.

**Comment by xastor** [comment]
I agree, great news!

**Comment by elsassph** [comment]
Can you guys try the branch? https://github.com/massiveinteractive/haxe-react/pull/20

**Comment by xastor** [comment]
Works like a charm over here, thanks!
