### ISSUE TITLE
PureComponent: invalid number of type parameters

### ISSUE THREAD

**Issue by djaonourside** [massiveinteractive/haxe-react#141]
https://github.com/massiveinteractive/haxe-react/blob/024988c157d3b86eaba69f434c75a5121a1e446e/src/lib/react/PureComponent.hx#L16
ReactComponentOf has only two type parameters.

**Comment by elsassph** [comment]
Fixed and released as 1.11.1

**Comment by kLabz** [comment]
@elsassph btw, are you interested in this for haxe-react? https://github.com/kLabz/haxe-react/commit/84ed997fb107684014bba206f81da2d7caac2e83
