### ISSUE TITLE
Support inline object declaration in jsx

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#15]
E.g. `jsx('<img style={{margin:0}}>')`

This should be achievable by properly matching the close braces

**Comment by elsassph** [comment]
I rewrote the parser with support for spread attributes among other improvements - this should land soon on github.

**Comment by kevinresol** [comment]
Nice!

**Comment by elsassph** [comment]
Can you try the branch? https://github.com/massiveinteractive/haxe-react/pull/20

**Comment by kevinresol** [comment]
Tested on my existing code base, both existing code and new features (inline object, double quote in attribute and spread operator) seem working well for me

**Comment by zabojad** [comment]
Same here. Existing code still compile and work file and new features work too... and that's awesome :)!
