### ISSUE TITLE
Mixins support

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#17]
I need the [mixins](https://facebook.github.io/react/docs/reusable-components.html#mixins) feature to use the [ReactIntl](http://formatjs.io/react/) lib.

I suppose we are subject to the [same limitation as ES6](https://facebook.github.io/react/docs/reusable-components.html#no-mixins) here?

**Comment by elsassph** [comment]
Yes, although macros could probably solve this problem.

**Comment by zabojad** [comment]
I think this concept might disappear in the next versions of react js in favour of the HOC factories concept...

**Comment by elsassph** [comment]
I also believe so.
