### ISSUE TITLE
Why not just `react` package name?

### ISSUE THREAD

**Issue by jeremyfa** [massiveinteractive/haxe-react#22]
I was wondering why the package name is `api.react` and not just `react`? It seems to me that the `api` intermediate package is not providing anything useful except noise in the code. At best I would just use the package name `react` (just like [here](https://github.com/fponticelli/react.hx) or [there](https://github.com/belliture/hxReact)) and at worst use `react.api` instead of `api.react` to have at least everything grouped into a common `react` package. I guess that your use of the `api` namespace might be related to the way you organize your packages internally, but I believe it would be best kept simple and as _internal-naming-convention-agnostic_ as possible, especially for a library as popular as React!

Anyway, that's a lot of text for a rather minor issue ;)

It's good to see some activity around Haxe for the React library (and looking forward to see the updated jsx parser :+1: ).

**Comment by elsassph** [comment]
Good guess for the reason it's in the `api` package ;)
We should consider renaming the package.

**Comment by kevinresol** [comment]
I would also like to get rid of the `api` package...

**Comment by elsassph** [comment]
Renaming that in PR #43 - please test.
