### ISSUE TITLE
src/view/TodoApp.hx:38: lines 38-47 : Invalid JSX: Expected =

### ISSUE THREAD

**Issue by MatthijsKamstra** [massiveinteractive/haxe-react#26]
Hi 

I tried the todo sample (https://github.com/massiveinteractive/haxe-react/tree/master/samples/todoapp) 

Got this message when building app:

```
src/view/TodoApp.hx:38: lines 38-47 : Invalid JSX: Expected =
```

**Comment by MatthijsKamstra** [comment]
maybe the haxelib version is not updated ? `Version: 0.2.0`

**Comment by MatthijsKamstra** [comment]
I just had time to test it.
The problem is fixed when you update the current files (version 0.3.0) to haxelib (still version 0.2.0)

**Comment by elsassph** [comment]
Yes we need to do the 0.3.0 release - the sample showcase the improved JSX parser.

**Comment by elsassph** [comment]
Try again with the new release!

**Comment by MatthijsKamstra** [comment]
fixed!
