### ISSUE TITLE
Can't wrap existing react component with externs

### ISSUE THREAD

**Issue by mcheshkov** [massiveinteractive/haxe-react#32]
When using existing react components, `setDisplayName` is trying to generate field for extern class.

``` haxe
extern class ExternComponent extends ReactComponent {}
```

This gives me `Extern non-inline variables may not be initialized`

Can be avoided by `if (inClass.isExtern) return null;` in `setDisplayName`

**Comment by elsassph** [comment]
Ouch :)

**Comment by mcheshkov** [comment]
Under 15 minutes! Thanks)
