### ISSUE TITLE
Unwrapped multiple tags in jsx silently generates different thing

### ISSUE THREAD

**Issue by mcheshkov** [massiveinteractive/haxe-react#34]
`jsx('<div>foo</div><div>bar</div>')` generates `return React.createElement("div",null,"foo");`
React's jsx fails with `SyntaxError: embedded: Adjacent JSX elements must be wrapped in an enclosing tag`

**Comment by elsassph** [comment]
Alright, Haxe's XML parser supports multiple roots; now raising an error as expected.
