### ISSUE TITLE
HTML text trimmed

### ISSUE THREAD

**Issue by mcheshkov** [massiveinteractive/haxe-react#38]
```
var b = jsx('<em>bbb</em>');
var a = jsx('<div><span>a</span> / {b}</div>'
```

Results in `React.createElement("div",null,React.createElement("span",null,"a"),"/ ",b);`

In actual jsx it's `React.createElement("div",null,React.createElement("span",null,"a")," / ",b);`

Notice lack of first space in `"/ "`

**Comment by mcheshkov** [comment]
Oh, it's even simpler `jsx('<span> </span>')` -> `React.createElement("span",null);` vs `React.createElement("span",null," ");`

**Comment by elsassph** [comment]
Yes, it's a known issue with the JSX interpreter.
