### ISSUE TITLE
Jsx issue with custom component named "Loading"

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#39]
I named one of my component `Loading`. In some of my other components where I'm using it, the haxe compilation sometimes generates things like this:

```
React.createElement("loading",null)
```

Instead of :

```
React.createElement(my_package_Loading,null)
```

The odd thing is that it does not generate this everywhere I use it.

**Comment by elsassph** [comment]
I suppose you're sure you have a capital L in Loading. Does it depend on surrounding tags?

**Comment by zabojad** [comment]
> I suppose you're sure you have a capital L in Loading

Yes, I am :).

> Does it depend on surrounding tags?

I have not identified conditions which make it happen. I renamed this component `Spinner` (which is more correct by the way) and I am not experiencing this issue anymore... There seem to be something with the name "Loading"...

**Comment by elsassph** [comment]
That sounds crazy... are you on master or on the literal branch?

**Comment by zabojad** [comment]
I am on master, commit de3c5574e62d54575f5e39f3b82c8f4165621e1e

**Comment by elsassph** [comment]
Can you try the optimization branch? It has a new parser.

**Comment by zabojad** [comment]
I've found where the issue came from.

I have an abstract enum in my code with all messages ids (for translations). One of them is `var Loading = "loading"`. In the components where I've imported this abstract enum, it seems the type resolution in the jsx code sometimes chose my abstract enum id `Loading` instead of my react component `Loading`.

Do you think the same would happen with the optimization branch?

**Comment by elsassph** [comment]
Type resolution will probably be identical with the new parser - enum values can shadow classes.

**Comment by elsassph** [comment]
PS: would be immensely useful if you can validate that the optimization branch works with your project (both debug and release mode).

**Comment by zabojad** [comment]
I will definitively do that. Have you summarized somewhere the changes that this branch brings?

**Comment by elsassph** [comment]
Right in fact master already has the new parser. 
The optimization branch #29 has a description of the changes and a link to the React discussion.
Basically, in release mode, instead of generating `React.createElements` we can generate literal JS objects `{$$typeof, type, props, ref, key}`.
