### ISSUE TITLE
Regarding limitations

### ISSUE THREAD

**Issue by fullofcaffeine** [massiveinteractive/haxe-react#4]
Hi,

First, great work with the lib. I'm getting into React and adding Haxe to the mix was something that was in the back of my head for some time, thanks for buidling and sharing this lib!

I'm curious about the following limitation:

```
You can't use functions (and thus factories) for stateless rendering. We're looking into this.
```

Do you mind providing a code example in the README depicting it? Also a short text explaining why it isn't possible with Haxe (and any possible workarounds) would be nice.

Thanks!

Thanks!

**Comment by elsassph** [comment]
If you don't know what "stateless functions" components you don't have to worry about it ;)

In practice it is about defining components as one static function with only one `props` parameter and it should behave like a render function.

Note that this isn't a Haxe limitation but rather a parser limitation.

**Comment by elsassph** [comment]
Turns out stateless functions can be used if you use a qualified static reference - I'll update  the readme.
