### ISSUE TITLE
Unsupported escaped char '{'

### ISSUE THREAD

**Issue by mcheshkov** [massiveinteractive/haxe-react#40]
I've just updated to libneko2 from PPA and now I get this error on any PCData element in jsx.
It come from `~/([^{]+|\{[^}]+\})/g` regexp in `ReactMacro.parseJsxNode`
Works nice in `~/([^{]+|{[^}]+})/g` form (notice lack of backslashes), but I don't know if this is proper PCRE and/or compatible with all Haxe platforms.

**Comment by elsassph** [comment]
You're right the backslash isn't needed, we'll remove it.
