### ISSUE TITLE
context argument in component constructor and other component methods...

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#41]
It seems that in the latest react version, the React.Component constructor and other React.Component methods like `componentWillReceiveProps` can take a `context` argument as parameter. Example here: https://github.com/reactjs/react-router/blob/c41309b3cd5ef5bf7e4b6e5219f0aba110557c7a/examples/animations/app.js#L22-L62

Right now this is now possible with haxe react... Is it just a matter or extending externs or is it more than that ?

**Comment by zabojad** [comment]
Actually, that might be deprecated but I cannot find the confirmation on reactjs docs... So I might have opened a non-issue :)...

**Comment by elsassph** [comment]
React team has always warned that it could be deprecated, but really libs like react-router or redux would not work without. However it doesn't seem critical to add context to the API as, with the exception of the absolutely discouraged `componentWillReceiveProps`, everything can be declared without problem.

**Comment by zabojad** [comment]
@elsassph What do you mean by `componentWillReceiveProps` being discouraged? Is its use discouraged? Why?

**Comment by elsassph** [comment]
That's what react documentation states.

What would you use it for? Context changes don't trigger willChange, and you get the context in the mount and render functions.

**Comment by zabojad** [comment]
OK, you mean the use of context is being discouraged, not the use of `componentWillReceiveProps`, right?

I agree, I do not use context anymore since all libs (router, intl, ...) now proposes a HOC alternative...

That ticket can be closed.

**Comment by elsassph** [comment]
I've added `context` in the constructor arguments.
