### ISSUE TITLE
[literals] generated JS contains api.react.React or api.react.ReactComponentOf

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#42]
Obviously they are incorrect because haxe classes with packages like that should be generated as `api_react_React` or `api_react_ReactComponentOf`.

I guess there are somewhere in the code that wrote `untyped api.react.React` so the compiler just generated them as-is.

I see this problem after the object-literal branch being merged.

**Comment by elsassph** [comment]
Ouch, can you provide a sample code where it happens?

**Comment by kevinresol** [comment]
I will get back to you soon

**Comment by kevinresol** [comment]
Hm... this seems a false report. I may have caused the problem due to some incorrect modifications from myself. Sorry for that.
