### ISSUE TITLE
Mysterious "untyped" in the macro?

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#44]
https://github.com/massiveinteractive/haxe-react/blob/5c397e5/src/lib/api/react/ReactMacro.hx#L209

Here, the `untyped` makes the function arguments untyped, it ignores typo or anything.
Can be fixed by wrapping a parenthesis: `return macro (untyped api.react.React._createElement)($a{args});`

But fundamentally why does the `untyped` exist at all?

**Comment by elsassph** [comment]
This function is private - there's probably a better way using the right meta.

**Comment by kevinresol** [comment]
@:privateAccess

**Comment by elsassph** [comment]
I resolved that by simply making the function non-private but with `@:noCompletion` meta.
