### ISSUE TITLE
JSX macro ignores any other elements after the first

### ISSUE THREAD

**Issue by TomasHubelbauer** [massiveinteractive/haxe-react#46]
``` haxe
return jsx('<h2>Messages</h2><ul>$messages</ul>');
```

This is not valid React code, because React currently doesn't support returning multiple elements from the render method: https://github.com/facebook/react/issues/2127

I think the macro should issue a warning where there is an attempt to return multiple elements. It could point the developer in the direction of wrapping the elements into a wrapper `div` or something like that.

I am not sure I can provide a PR for this until I learn a little more Haxe so I'm just letting it be known for now.

**Comment by elsassph** [comment]
Fixed in master (raises a compiler error)
