### ISSUE TITLE
We shouldn't define getInitialState() ?

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#5]
I'm getting this warning at runtime if I define a getInitialState method in my React components:

```
Warning: getInitialState was defined on AppView, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
```

So I guess we should set this.state right in the constructor ?

That may be useful to document briefly all the deltas with using Rect with and without Haxe...

**Comment by elsassph** [comment]
Could you show the exact code?

**Comment by zabojad** [comment]
Basically, the important part is just:

```
// ...

typedef AppViewState = {
    pages : Array<PageType>
}

class AppView extends ReactComponentOf<Dynamic, AppViewState, Dynamic> {

    public function new() {

        super();

        this.state = getInitialState(); // I have to do this, although in React doc, it's said that when a component has a state, it can define a getInitialState() method that will be called (by React) once at component instantiation...
    }

    // ...

    function getInitialState() : AppViewState { // I was expecting to have to put "override" here but it's apparently not part of haxe-react...

        return { pages: [] };
    }
// ...
```

**Comment by elsassph** [comment]
It looks like `getInitialState` isn't recommended (and automatic) when using classes:
http://stackoverflow.com/questions/31709258/why-is-getinitialstate-not-being-called-for-my-react-class

It's a kind of helper for when using the `React.CreateClass` pattern; just set the initial state in your constructor.
