### ISSUE TITLE
Inline mode doesn't respect `defaultProps`?

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#57]
I am not particularly sure if I am talking the right thing. But seems that react's `createElement` will try to copy some props from the type's static var `defaultProps` if a key doesn't exists. But our macro's inline mode doesn't seem to do that, causing some breakages on components that rely on it.

ref: https://github.com/facebook/react/blob/6810627a91f2020caee7fecf21580187dc6ef0fc/src/isomorphic/classic/element/ReactElement.js#L232-L239

**Comment by elsassph** [comment]
No you're absolutely right - we should apply the default props in the JSON object.

**Comment by elsassph** [comment]
@kevinresol please check PR #59 and tell me if the result is ok - I'll need to refactor a bit probably to add some unit tests.

**Comment by kevinresol** [comment]
I was using an extern component, so I guess the macro need to put in some runtime check for the existence of defaultProps in case of external class?

**Comment by elsassph** [comment]
Ah damn, we can't do that. Macros don't run in JS; I guess Babel can do this discovery but we can't.

Ok I'll simply add back the guard to NOT inline extern components.

**Comment by kevinresol** [comment]
Well I mean you just use macro to generate some expressions like
`type.defaultProps == null ? props : Object.assign({}, type.defaultProps, props)`
and put that in the inline element code. If it is an extern class.

**Comment by elsassph** [comment]
Hmmm maybe yes. 

Can be a bit convoluted because `props` in your example will be either a literal object or `Object.assign` for spreads. You wouldn't want to be redundant, and we can't easily use intermediary variables, which means it may not be a lot more efficient than the default `createElement` call.

**Comment by elsassph** [comment]
I pushed a depot for extern react components - it's safer like that and doesn't require a runtime replacement of `React.createElement` like babel do (see babel-helpers).

**Comment by elsassph** [comment]
For what it's worth, Babel does use a runtime helper function - our compile-time literals are much more powerful for everything that isn't an extern!
