### ISSUE TITLE
Using external lib won't compile anymore

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#60]
I've just updated my haxe-react (I was still using a version from April) and now, because of this:
```
typedef CreateElementType = haxe.extern.EitherType<haxe.extern.EitherType<String, haxe.Constraints.Function>, Class<ReactComponent>>;
```
I cannot use extern classes like this for example:
```
@:jsRequire('react-redux', 'Provider')
extern class Provider { }

// ...

return jsx('
  <Provider store={store}>
    <Application />
  </Provider>
');
```

It seems the JSX macro now enforces elements to be either Strings, functions or classes extended ReactComponent...

Is there any solution to declare an extern class as extending ReactComponent ? Or should I write wrapping Haxe React component for every external component I want to use?

**Comment by zabojad** [comment]
Wow, I've just come accross closed issues and more particularly that one: https://github.com/massiveinteractive/haxe-react/issues/32

So it seems this
```
@:jsRequire('react-redux', 'Provider')
extern class Provider extends react.ReactComponent { }
```
is actually valid and works...

**Comment by elsassph** [comment]
Yeah this is a bit unfortunate but we have to specify the base class now.

**Comment by elsassph** [comment]
I added a note in the readme about that.
