### ISSUE TITLE
Statics in TODO app

### ISSUE THREAD

**Issue by markknol** [massiveinteractive/haxe-react#62]
Hi, I'm checking out/learning react for first time. I'm excited I can use Haxe for this 😄 

Question: I wonder if it is needed/preferred to have the statics in TodoActions, or how would this be solved otherwise?

Especially this one https://github.com/massiveinteractive/haxe-react/blob/master/samples/todoapp/src/view/TodoApp.hx#L63

**Comment by markknol** [comment]
I found it, I've added the TodoActions signals to the TodoStore, and passed the store in the props of the TodoList

```
<$TodoList store=${todoStore} ...
```
Overall it seems to works very smooth, thanks for your works on this!

**Comment by elsassph** [comment]
This sample, although a bit naive, follows the suggested Flux architecture, where store (model) and actions (intents/commands) should be decoupled. 

In any case I don't recommend passing the store reference to the list. The correct pattern in React apps is to pass callbacks in the props.

Check the other 2 samples (redux and mmvc ones) - they follow much more scalable.
