### ISSUE TITLE
setState also accepts function

### ISSUE THREAD

**Issue by kevinresol** [massiveinteractive/haxe-react#65]
TL;DR: `setState` should also accept `TState->TProps->TState` as argument

https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1#.2pnif19v4

**Comment by TomasHubelbauer** [comment]
https://github.com/massiveinteractive/haxe-react/blob/master/src/lib/react/ReactComponent.hx#L48-L49

I've put this in a couple of weeks back. Is that what you have in mind?

EDIT: Changed to the overload lines.

**Comment by elsassph** [comment]
No we need to allow passing a function (TState -> TState) instead of directly providing the TState object.

**Comment by elsassph** [comment]
Oh actually the overload allows it already - sounds good to close.
