### ISSUE TITLE
Invalid JSX

### ISSUE THREAD

**Issue by dionjwa** [massiveinteractive/haxe-react#69]
Just getting starting with react and haxe, but I'm hitting a jsx compilation issue I can't seem to fix no matter how I rearrange and tweak the jsx.

I've labeled line 82 that the compiler complains about:

```
return jsx('

			<InfiniteLoader
				isRowLoaded={isRowLoaded}
				loadMoreRows={loadMoreRows}
				rowCount={rowCount}
			>
				{({ onRowsRendered, registerChild }) => (
					<List
82:						ref={registerChild}
						onRowsRendered={onRowsRendered}
						rowRenderer={rowRenderer}
						{...otherProps}
					/>
				)}
			</InfiniteLoader>
		');

```

Gives this error:
```src/example/todo/view/GalleryView.hx:82: lines 82-99 : Invalid JSX: Expected "```

Any ideas?

**Comment by elsassph** [comment]
You have some ES6 copy-pasta here :)

The child of the `<InfiniteLoader>` tag is using fancy ES6 syntax:
```haxe
// ES6 arrow-function and argument deconstruction
({ onRowsRendered, registerChild }) => (<List.../>)

// Haxe
function (op) {
    var onRowsRendered = op.onRowsRendered;
    var registerChild = op.registerChild;
    return jsx('<List.../>')
}
```

When you replace the function you may have to cast it to Dynamic if the compiler complains it's not a valid child value.

**Comment by dionjwa** [comment]
Oh great, thanks! Quite a lot of language mix and match here. And yes, I was trying to get the InfiniteLoader running by their example :)
