### ISSUE TITLE
Is it possible to use dynamic content with this?

### ISSUE THREAD

**Issue by Jarrio** [massiveinteractive/haxe-react#73]
So I've been using this for a little while and gotten 1 or 2 apps working with it. But I've come to a situation - I want to use emoji in my current project and have to parse the content (which works fine). The library for [emoji is a react-native](https://github.com/jorilallo/react-native-emoji) one but I believe this is an issue? with `jsx()` rather than native export.

```haxe
	private function parseEmoji(content:String):Dynamic {
		var match:EReg = ~/:([a-z0-9_]+):/g;
		if (content != null) {
			content = match.replace(content, '<Emoji name="$1" />');		
		}
		return content;
	}
```

So that would give me something like `:coffee: test emoji` to `<Emoji name="coffee" />` which then becomes valid jsx syntax. When returning the code I then do
```haxe
var emojify = this.parseEmoji(":coffee: test emoji");
var content = jsx('<Text style={styles.content}>$emojify</Text>');
```

but instead of parsing the `$emojify` as jsx code, it would print it literally as the replacement 
(`<Emoji name="coffee" /> test emoji`). Is there a way around this?

**Comment by elsassph** [comment]
Expression in JSX is not a "run time String", it's a "compile time" String parsed as XML and replaced by Haxe code. 

One way to do what you want to do would be to emit raw HTML and set it using the "dangerously set html" feature of React.
