### ISSUE TITLE
haxe-react-mmvc-master => empty page on apache 

### ISSUE THREAD

**Issue by axelhuizinga** [massiveinteractive/haxe-react#74]
Hi,
this is the content chrome dev tools see on the url http://localhost/devel/bin/ after copying the whole bin tree into the apache document root - no errors on the console:
<html><head>
	<title>React Mmvc</title>
	<script>
	if (!Object.assign || typeof Promise === 'undefined') {
		document.write('<script src="//cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.min.js"></'+'script>');
		document.write('<script src="//cdnjs.cloudflare.com/ajax/libs/dom4/1.8.3/dom4.js"></'+'script>');
	}
	</script>
</head>
<body>
	<link rel="stylesheet" href="css/index.css">
	<script src="libs.js"></script>
	<script src="index.js"></script><div></div>

</body></html>

**Comment by elsassph** [comment]
What do you have in Chrome's Network tab?

**Comment by axelhuizinga** [comment]
Only this one:
Navigated to http://localhost/devel/bin/
index.css, libs.js and index.js got loaded too

**Comment by elsassph** [comment]
If nothing happens there must be an error at some point and you must troubleshoot the JS execution - inspect and try adding a breakpoint in your index.js.

PS: wrong Github project to report your problem.

**Comment by axelhuizinga** [comment]
Sorry for reporting within the wrong project but the solution applies to any use of react-router I guess:
I had to prefix all path attributes with /devel/bin/
maybe it's better to rewrite with htaccess?
is live-reload possible with apache?

**Comment by elsassph** [comment]
Ah react-router wants to be at the root of the server...
