### ISSUE TITLE
jsx syntax for inline if-else operator

### ISSUE THREAD

**Issue by tbrannam** [massiveinteractive/haxe-react#76]
I'm looking at some different styles of JSX syntax and haven't been able to adapt haxe-react's JSX to support this conditional syntax.

Is this a supported syntax?  I suspect that the JSX macro parser has limits that I'm running into?

This simple structure works, the expression results in either 'online' or 'offline' returned as a string

```
${ AuthenticationService.isLoggedIn() ? ('online') : ('offline')}
```

But am unable to return conditional elements - the entire expression is treated as string
```
${ AuthenticationService.isLoggedIn() ? (<span>online<span/>) : (<span>offline<span/>)}
```

Here's the relevant JSX syntax I'm working to implement 

https://facebook.github.io/react/docs/conditional-rendering.html#inline-if-else-with-conditional-operator
```
<div>
      {isLoggedIn ? (
        <LogoutButton onClick={this.handleLogoutClick} />
      ) : (
        <LoginButton onClick={this.handleLoginClick} />
      )}
    </div>
```

**Comment by elsassph** [comment]
That's because everytime you have something like `<span>online</span>`, with or without parenthesis, it has to be like `jsx('<span>online</span>')`. 

You have to realise that JSX is transformed into JSON objects ("React Elements") with children defined as an array of other JSON objects (or strings if you have text literals) - it's not string magic.

In JS/TS you have a DSL where you can directly use the pseudo XML, while in Haxe it has to look like `jsx('some JSX literal')`.

So the FB example should be: **[Edit: this doesn't work! JSX calls can't be nested]**
```haxe
return jsx('
   <div>
      ${isLoggedIn ? jsx('
        <LogoutButton onClick=${this.handleLogoutClick} />
      ') : jsx('
        <LoginButton onClick=${this.handleLoginClick} />
      ')}
  </div>
');
```

Which is transformed into: **[Edit: we wish it was :D]**
```haxe
React.createElement('div', null, [
    isLoggedIn ? React.createElement(LogoutButton, { onClick:this.handleLogoutClick })
    : React.createElement(LoginButton, { onClick:this.handleLogingClick })
]);
```

**Comment by tbrannam** [comment]
that is what I sort of expected, but I'm getting the wrong result with that format

```
return jsx('<div>
    ${true ? jsx('<span>online</span>') : jsx('<span>offline</span>')}
</div>');
```
renders as 
```
<div data-reactroot=""><!-- react-text: 3 -->true ? jsx('<!-- /react-text --><span>online</span><!-- react-text: 5 -->') : jsx('<!-- /react-text --><span>offline</span><!-- react-text: 7 -->')}<!-- /react-text --></div>
```

**Comment by elsassph** [comment]
Oh actually we have a real limitation about nesting JSX calls so code has to be split.
```haxe
var button = isLoggedIn ? jsx('
    <LogoutButton onClick=${this.handleLogoutClick} />
') : jsx('
    <LoginButton onClick=${this.handleLoginClick} />
');

return jsx('
   <div>${button}</div>
');
```

**Comment by elsassph** [comment]
Solution to this need will be to introduce `<if>` type of tags - may be coming with the hxx parser migration.

**Comment by kLabz** [comment]
@tbrannam FYI @elsassph's mentioned hxx parser migration is usable from [this fork](https://github.com/kLabz/haxe-react/) (or haxelib `react-next`) with said `<if {condition}>` tags and more.
