### ISSUE TITLE
PropTypes moved to separate repository

### ISSUE THREAD

**Issue by Misiur** [massiveinteractive/haxe-react#78]
[Orange box here](https://facebook.github.io/react/docs/typechecking-with-proptypes.html). I think it starts with React 15.5

**Comment by elsassph** [comment]
Yes, the require has be changed in https://github.com/massiveinteractive/haxe-react/blob/master/src/lib/react/ReactPropTypes.hx

Which reminds me this file isn't compatible with `-D react_global` option.

**Comment by elsassph** [comment]
Now fixed, and compatible with `-D react_global`
