### ISSUE TITLE
No changes concerning react 16 in the haxelib library version

### ISSUE THREAD

**Issue by djaonourside** [massiveinteractive/haxe-react#83]
The latest haxelib version is 1.2.1 and there is no react 16 changes here.

**Comment by elsassph** [comment]
Yes, I slept on a last PR for React 16... master branch is now fully compatible and needs to be pushed to haxelib.

**Comment by djaonourside** [comment]
Excuse my importunity, any progress on haxelib publishing?

**Comment by elsassph** [comment]
It's now published as `1.3.0`
