### ISSUE TITLE
Functional components is shown as <Unknow>...</Unknow> in chrome dev tools

### ISSUE THREAD

**Issue by djaonourside** [massiveinteractive/haxe-react#84]
Using optional meta @:jsxStatic leads to incorrect displaying of the compontent name in chrome dev tools:  `<Unknow>...</Unknow>`

**Comment by elsassph** [comment]
That's because Haxe doesn't generate function names, we need to look into giving it a `displayName` like component classes.

**Comment by kLabz** [comment]
I'll see if I can do something about it

**Comment by elsassph** [comment]
PR #86 was merged, can you try with the haxelib from git?

**Comment by kLabz** [comment]
It should even be in 1.4.0 :)

**Comment by djaonourside** [comment]
With haxe 4-preview4 and haxe react dev it doesn't work again :(

**Comment by djaonourside** [comment]
Haxe 4-preview 4, haxe-react dev

build-dev.hxml: 
`build.hxml
-D debug
-D develop
-D react_hot
-D react_render_warning`

Build cases
1) haxe.exe --connect 6000 build-dev.hxml (vscode haxe build task)
2) haxe.exe  build-dev.hxml (cmd)
The cases give different output. In the first case displayName for a functional component disappears.

**Comment by kLabz** [comment]
Strange, I remember testing with compilation server back then. I'll try to reproduce and fix.

**Comment by djaonourside** [comment]
I suspect haxe compiler doesn't see debug flag in the first case

**Comment by kLabz** [comment]
It should.

I reproduced and have a fix, I'll push a PR.

**Comment by djaonourside** [comment]
Thank you:)

**Comment by kLabz** [comment]
If you want to try the fix, you can install haxe-react like this:
```
haxelib git react https://github.com/kLabz/haxe-react.git fix/jsxstatic-displayname-compilation-server
```
