### ISSUE TITLE
Inline mode issue?

### ISSUE THREAD

**Issue by zabojad** [massiveinteractive/haxe-react#98]
I'm note sure it's really an issue actually. Let me detail the problem:

When switching to inline mode, I receive a lot of `Each iterator should have a unique “key” prop` errors that I do not get normally...

It happens because of the way components are inlined by haxe-react.

Let's take a little sample JSX snippet:
```
return jsx('
	<Toolbar className="HeaderToolbar">
		<div className="left">
			<ToolbarButton onClick={toggleMenu}>
				<Icon icon="fa-bars" />
			</ToolbarButton>
			{ renderBackBtn() }
		</div>
		<div className="center">
			<Touchable onTouchTap={homeCb} className="logoBtn">
				<img src={logoImg} />
			</Touchable>
		</div>
		<div className="right">
			{ renderRightPart() }
		</div>
	</Toolbar>
');
```

When not inlining, it will translate to :
```
var tmp = React.createElement(ons_react_Icon,{ icon : "fa-bars"});
var tmp1 = React.createElement(ons_react_ToolbarButton,{ onClick : $bind(this,this.toggleMenu)},tmp);
var tmp2 = this.renderBackBtn();
var tmp3 = React.createElement("div",{ className : "left"},tmp1,tmp2);
var tmp4 = React.createElement("img",{ src : test_view_cmp_HeaderToolbar.logoImg});
var tmp5 = React.createElement(test_view_generic_Touchable,{ onTouchTap : $bind(this,this.homeCb), className : "logoBtn"},tmp4);
var tmp6 = React.createElement("div",{ className : "center"},tmp5);
var tmp7 = this.renderRightPart();
var tmp8 = React.createElement("div",{ className : "right"},tmp7);
return React.createElement(ons_react_Toolbar,{ className : "HeaderToolbar"},tmp3,tmp6,tmp8);
```
Everything OK here...

Now when inlining, here is what we get:
```
var tmp = $$tre;
var tmp1 = React.createElement(ons_react_Icon,{ icon : "fa-bars"});
var tmp2 = { $$typeof : tmp, type : "div", props : { className : "left", children : [React.createElement(ons_react_ToolbarButton,{ onClick : $bind(this,this.toggleMenu)},tmp1),this.renderBackBtn()]}, key : null, ref : null};
var tmp3 = { "$$typeof" : $$tre, type : "div", props : { className : "center", children : { "$$typeof" : $$tre, type : test_view_generic_Touchable, props : { onTouchTap : $bind(this,this.homeCb), className : "logoBtn", children : { "$$typeof" : $$tre, type : "img", props : { src : test_view_cmp_HeaderToolbar.logoImg}, key : null, ref : null}}, key : null, ref : null}}, key : null, ref : null};
var tmp4 = $$tre;
var tmp5 = this.renderRightPart();
return React.createElement(ons_react_Toolbar,{ className : "HeaderToolbar"},tmp2,tmp3,{ $$typeof : tmp4, type : "div", props : { className : "right", children : tmp5}, key : null, ref : null});
```

We can see that this inlining mode had the bad idea :D to put the children of the `.HeaderToolbar .left` `div` into an array without giving each of those children a key...

Maybe it works as designed but wouldn't it be better to either:
- give those child a auto generated key in this specific case 
or
- avoid using an array here (if that's possible)

**Comment by elsassph** [comment]
It's not a bug - keys shouldn't be added automatically.
The problem is when you use Haxe-release with React-debug library.

Babel also has an inliner plugin which causes the same warning to happen: https://github.com/facebook/react/issues/10352

**Comment by zabojad** [comment]
Hmm so the way to go is to manually put keys everywhere we have more than one child? Too bad we cannot automate it somehow...

**Comment by elsassph** [comment]
Of course not! 
The warning is only meant to warn people doing an actual array of items without adding a key.

The way to go is to use production version of React when you compile haxe for release.

**Comment by zabojad** [comment]
@elsassph so you mean we just ignore this warning (in those cases) and use production version of React, is that right?

**Comment by kLabz** [comment]
That's more or less what Dan Abramov said on the issue @elsassph linked to.

**Comment by zabojad** [comment]
OK I got it, thank you for your answers guys!
