### ISSUE TITLE
The lib doesn't work with haxe 4 preview

### ISSUE THREAD

**Issue by djaonourside** [massiveinteractive/haxe-react#99]

**Comment by kLabz** [comment]
I have a fix somewhere, I'll try to make a PR tonight.

**Comment by kLabz** [comment]
Actually it's already merged (#91), but there have been no release since november.

@djaonourside : you may want to use git version in the meantime, with `haxelib git react git@github.com:massiveinteractive/haxe-react.git`

**Comment by djaonourside** [comment]
@kLabz Thank you. I'll try it.

**Comment by kLabz** [comment]
Should work with `haxe-react` 1.4.0, unless you have some issues we haven't encountered.

Could you confirm, please?

**Comment by djaonourside** [comment]
I have no problems with haxe-react 1.4.0 and haxe 4 preview in my projects. Thank you:)
